LIST_COMMISSION_DATA = (
    {'comm': 'Vein Protection Commission Ⅰ', 'cn': ('初级矿脉护卫委托', ''), 'en': ('VEINPROTECTIONCOMMISSION', 'Ⅰ'), 'jp': ('初級鉄鋼輸送護衛', ''), 'tw': ('初級礦脈護衛委託', ''), 'duration': '0:30:00', 'expiration': '0:00:00'},
    {'comm': 'Forest Protection Commission Ⅰ', 'cn': ('初级林木护卫委托', ''), 'en': ('FORESTPROTECTIONCOMMISSION', 'Ⅰ'), 'jp': ('初級木材輸送護衛', ''), 'tw': ('初級林木護衛委託', ''), 'duration': '0:30:00', 'expiration': '0:00:00'},
    {'comm': 'Small Merchant Escort', 'cn': ('小型商船护卫', ''), 'en': ('SMALLMERCHANTESCORT', ''), 'jp': ('小型船団護衛', ''), 'tw': ('小型商船護衛', ''), 'duration': '5:00:00', 'expiration': '0:00:00'},
    {'comm': 'Short-range Sailing Training', 'cn': ('短距离航行训练', ''), 'en': ('SHORTRANGESAILINGTRAINING', ''), 'jp': ('短距離練習航海', ''), 'tw': ('短距離航行訓練', ''), 'duration': '0:20:00', 'expiration': '0:00:00'},
    {'comm': 'Fleet Escort Exercise', 'cn': ('舰队护卫演习', ''), 'en': ('FLEETESCORTEXERCISE', ''), 'jp': ('船団護衛演習', ''), 'tw': ('艦隊護衛演習', ''), 'duration': '0:30:00', 'expiration': '0:00:00'},
    {'comm': 'Coastal Defense Patrol', 'cn': ('近海防卫巡逻', ''), 'en': ('COASTALDEFENSEPATROL', ''), 'jp': ('近海防衛巡回', ''), 'tw': ('近海防衛巡邏', ''), 'duration': '2:40:00', 'expiration': '0:00:00'},
    {'comm': 'Fleet Exercise Ⅰ', 'cn': ('舰队初阶演习', ''), 'en': ('FLEETEXERCISE', 'Ⅰ'), 'jp': ('装備慣熟演習', ''), 'tw': ('艦隊初階演習', ''), 'duration': '4:00:00', 'expiration': '0:00:00'},
    {'comm': 'Small-scale Oil Extraction Ⅰ', 'cn': ('小型油田开发', 'Ⅰ'), 'en': ('SMALLSCALEOILEXTRACTION', 'Ⅰ'), 'jp': ('小型油田開発', 'Ⅰ'), 'tw': ('小型油田開發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Mid-scale Oil Extraction Ⅰ', 'cn': ('中型油田开发', 'Ⅰ'), 'en': ('MIDSCALEOILEXTRACTION', 'Ⅰ'), 'jp': ('中型油田開発', 'Ⅰ'), 'tw': ('中型油田開發', 'Ⅰ'), 'duration': '4:00:00', 'expiration': '0:00:00'},
    {'comm': 'Large-scale Oil Extraction Ⅰ', 'cn': ('大型油田开发', 'Ⅰ'), 'en': ('LARGESCALEOILEXTRACTION', 'Ⅰ'), 'jp': ('大型油田開発', 'Ⅰ'), 'tw': ('大型油田開發', 'Ⅰ'), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Vein Protection Commission Ⅱ', 'cn': ('中级矿脉护卫委托', ''), 'en': ('VEINPROTECTIONCOMMISSION', 'Ⅱ'), 'jp': ('中級鉄鋼輸送護衛', ''), 'tw': ('中級礦脈護衛委託', ''), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Forest Protection Commission Ⅱ', 'cn': ('中级林木护卫委托', ''), 'en': ('FORESTPROTECTIONCOMMISSION', 'Ⅱ'), 'jp': ('中級木材輸送護衛', ''), 'tw': ('中級林木護衛委託', ''), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Medium Merchant Escort', 'cn': ('中型商船护卫', ''), 'en': ('MEDIUMMERCHANTESCORT', ''), 'jp': ('中型船団護衛', ''), 'tw': ('中型商船護衛', ''), 'duration': '6:00:00', 'expiration': '0:00:00'},
    {'comm': 'Mid-range Sailing Training', 'cn': ('中距离航行训练', ''), 'en': ('MIDRANGESAILINGTRAINING', ''), 'jp': ('中距離練習航海', ''), 'tw': ('中距離航行訓練', ''), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Fleet Cargo Transport', 'cn': ('舰队运输演习', ''), 'en': ('FLEETCARGOTRANSPORT', ''), 'jp': ('艦隊輸送演習', ''), 'tw': ('艦隊運輸演習', ''), 'duration': '1:30:00', 'expiration': '0:00:00'},
    {'comm': 'Buoy Inspection', 'cn': ('海域浮标检查作业', ''), 'en': ('BUOYINSPECTION', ''), 'jp': ('海域浮標保守作業', ''), 'tw': ('海域浮標檢查作業', ''), 'duration': '3:20:00', 'expiration': '0:00:00'},
    {'comm': 'Fleet Exercise Ⅱ', 'cn': ('舰队中阶演习', ''), 'en': ('FLEETEXERCISE', 'Ⅱ'), 'jp': ('艦隊慣熟演習', ''), 'tw': ('艦隊中階演習', ''), 'duration': '5:00:00', 'expiration': '0:00:00'},
    {'comm': 'Small-scale Oil Extraction Ⅱ', 'cn': ('小型油田开发', 'Ⅱ'), 'en': ('SMALLSCALEOILEXTRACTION', 'Ⅱ'), 'jp': ('小型油田開発', 'Ⅱ'), 'tw': ('小型油田開發', 'Ⅱ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Mid-scale Oil Extraction Ⅱ', 'cn': ('中型油田开发', 'Ⅱ'), 'en': ('MIDSCALEOILEXTRACTION', 'Ⅱ'), 'jp': ('中型油田開発', 'Ⅱ'), 'tw': ('中型油田開發', 'Ⅱ'), 'duration': '4:00:00', 'expiration': '0:00:00'},
    {'comm': 'Large-scale Oil Extraction Ⅱ', 'cn': ('大型油田开发', 'Ⅱ'), 'en': ('LARGESCALEOILEXTRACTION', 'Ⅱ'), 'jp': ('大型油田開発', 'Ⅱ'), 'tw': ('大型油田開發', 'Ⅱ'), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Vein Protection Commission Ⅲ', 'cn': ('高级矿脉护卫委托', ''), 'en': ('VEINPROTECTIONCOMMISSION', 'Ⅲ'), 'jp': ('上級鉄鋼輸送護衛', ''), 'tw': ('高級礦脈護衛委託', ''), 'duration': '1:30:00', 'expiration': '0:00:00'},
    {'comm': 'Forest Protection Commission Ⅲ', 'cn': ('高级林木护卫委托', ''), 'en': ('FORESTPROTECTIONCOMMISSION', 'Ⅲ'), 'jp': ('上級木材輸送護衛', ''), 'tw': ('高級林木護衛委託', ''), 'duration': '1:30:00', 'expiration': '0:00:00'},
    {'comm': 'Large Merchant Escort', 'cn': ('大型商船护卫', ''), 'en': ('LARGEMERCHANTESCORT', ''), 'jp': ('大型船団護衛', ''), 'tw': ('大型商船護衛', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Long-range Sailing Training', 'cn': ('远距离航行训练', ''), 'en': ('LONGRANGESAILINGTRAINING', ''), 'jp': ('外洋練習航海', ''), 'tw': ('遠距離航行訓練', ''), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Fleet Combat Exercise', 'cn': ('舰队实战演习', ''), 'en': ('FLEETCOMBATEXERCISE', ''), 'jp': ('艦隊実弾演習', ''), 'tw': ('艦隊實戰演習', ''), 'duration': '3:00:00', 'expiration': '0:00:00'},
    {'comm': 'Frontier Defense Patrol', 'cn': ('前沿基地防卫巡逻', ''), 'en': ('FRONTIERDEFENSEPATROL', ''), 'jp': ('前線基地防衛巡回', ''), 'tw': ('前線基地防衛巡邏', ''), 'duration': '5:20:00', 'expiration': '0:00:00'},
    {'comm': 'Fleet Exercise Ⅲ', 'cn': ('舰队高阶演习', ''), 'en': ('FLEETEXERCISE', 'Ⅲ'), 'jp': ('艦隊運動演習', ''), 'tw': ('艦隊高階演習', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Small-scale Oil Extraction Ⅲ', 'cn': ('小型油田开发', 'Ⅲ'), 'en': ('SMALLSCALEOILEXTRACTION', 'Ⅲ'), 'jp': ('小型油田開発', 'Ⅲ'), 'tw': ('小型油田開發', 'Ⅲ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Mid-scale Oil Extraction Ⅲ', 'cn': ('中型油田开发', 'Ⅲ'), 'en': ('MIDSCALEOILEXTRACTION', 'Ⅲ'), 'jp': ('中型油田開発', 'Ⅲ'), 'tw': ('中型油田開發', 'Ⅲ'), 'duration': '4:00:00', 'expiration': '0:00:00'},
    {'comm': 'Large-scale Oil Extraction Ⅲ', 'cn': ('大型油田开发', 'Ⅲ'), 'en': ('LARGESCALEOILEXTRACTION', 'Ⅲ'), 'jp': ('大型油田開発', 'Ⅲ'), 'tw': ('大型油田開發', 'Ⅲ'), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Aiding Vella Lavella', 'cn': ('支援维拉维拉岛', ''), 'en': ('AIDINGVELLALAVELLA', ''), 'jp': ('近海掃海任務', ''), 'tw': ('支援維拉維拉島', ''), 'duration': '0:30:00', 'expiration': '2:00:00'},
    {'comm': "Aiding Tyrant's Island", 'cn': ('支援土豪尔岛', ''), 'en': ('AIDINGTYRANTSISLAND', ''), 'jp': ('離島物資輸送', ''), 'tw': ('支援土豪爾島', ''), 'duration': '0:30:00', 'expiration': '2:00:00'},
    {'comm': 'Cargo Defense Ⅰ', 'cn': ('保卫运输部队', 'Ⅰ'), 'en': ('CARGODEFENSE', 'Ⅰ'), 'jp': ('輸送部隊護衛', 'Ⅰ'), 'tw': ('保衛運輸部隊', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '3:00:00'},
    {'comm': 'Merchant Rescue Ⅰ', 'cn': ('解救商船', 'Ⅰ'), 'en': ('MERCHANTRESCUE', 'Ⅰ'), 'jp': ('船団救出', 'Ⅰ'), 'tw': ('解救商船', 'Ⅰ'), 'duration': '1:30:00', 'expiration': '3:00:00'},
    {'comm': 'BIW Gear Transport', 'cn': ('BIW装备运输', ''), 'en': ('BIWGEARTRANSPORT', ''), 'jp': ('BIW装備輸送', ''), 'tw': ('BIW裝備運輸', ''), 'duration': '1:00:00', 'expiration': '5:20:00'},
    {'comm': 'NYB Gear Transport', 'cn': ('NYB装备运输', ''), 'en': ('NYBGEARTRANSPORT', ''), 'jp': ('NYB装備輸送', ''), 'tw': ('NYB裝備運輸', ''), 'duration': '1:00:00', 'expiration': '5:20:00'},
    {'comm': 'Aiding Maui', 'cn': ('支援伊岛', ''), 'en': ('AIDINGMAUI', ''), 'jp': ('近海航行展示', ''), 'tw': ('支援伊島', ''), 'duration': '1:00:00', 'expiration': '2:00:00'},
    {'comm': 'Aiding Poro', 'cn': ('支援姆波罗岛', ''), 'en': ('AIDINGPORO', ''), 'jp': ('近海パトロール', ''), 'tw': ('支援姆波羅島', ''), 'duration': '1:00:00', 'expiration': '2:00:00'},
    {'comm': 'Destroy Enemy Scouts', 'cn': ('歼灭敌侦查部队', ''), 'en': ('DESTROYENEMYSCOUTS', ''), 'jp': ('敵偵察部隊迎撃', ''), 'tw': ('殲滅敵偵查部隊', ''), 'duration': '1:10:00', 'expiration': '2:20:00'},
    {'comm': 'Enemy Attack Ⅰ', 'cn': ('敌袭', 'Ⅰ'), 'en': ('ENEMYATTACK', 'Ⅰ'), 'jp': ('敵襲', 'Ⅰ'), 'tw': ('敵襲', 'Ⅰ'), 'duration': '1:45:00', 'expiration': '2:20:00'},
    {'comm': 'BIW VIP Escort', 'cn': ('BIW要员护卫', ''), 'en': ('BIWVIPESCORT', ''), 'jp': ('BIW要人護衛', ''), 'tw': ('BIW要員護衛', ''), 'duration': '2:00:00', 'expiration': '5:20:00'},
    {'comm': 'NYB VIP Escort', 'cn': ('NYB要员护卫', ''), 'en': ('NYBVIPESCORT', ''), 'jp': ('NYB要人護衛', ''), 'tw': ('NYB要員護衛', ''), 'duration': '2:00:00', 'expiration': '5:20:00'},
    {'comm': 'Small Launch Ceremony', 'cn': ('小型观舰仪式', ''), 'en': ('SMALLLAUNCHCEREMONY', ''), 'jp': ('小型観艦式', ''), 'tw': ('小型觀艦儀式', ''), 'duration': '3:00:00', 'expiration': '6:00:00'},
    {'comm': 'Aiding Rendova Island', 'cn': ('支援多伦瓦岛', ''), 'en': ('AIDINGRENDOVAISLAND', ''), 'jp': ('離島火力支援', ''), 'tw': ('支援多倫瓦島', ''), 'duration': '1:20:00', 'expiration': '5:00:00'},
    {'comm': 'Aiding Makira', 'cn': ('支援马拉基岛', ''), 'en': ('AIDINGMAKIRA', ''), 'jp': ('離島漸減支援', ''), 'tw': ('支援馬拉基島', ''), 'duration': '1:20:00', 'expiration': '5:00:00'},
    {'comm': 'Cargo Defense Ⅱ', 'cn': ('保卫运输部队', 'Ⅱ'), 'en': ('CARGODEFENSE', 'Ⅱ'), 'jp': ('輸送部隊護衛', 'Ⅱ'), 'tw': ('保衛運輸部隊', 'Ⅱ'), 'duration': '1:30:00', 'expiration': '3:20:00'},
    {'comm': 'Merchant Rescue Ⅱ', 'cn': ('解救商船', 'Ⅱ'), 'en': ('MERCHANTRESCUE', 'Ⅱ'), 'jp': ('船団救出', 'Ⅱ'), 'tw': ('解救商船', 'Ⅱ'), 'duration': '2:15:00', 'expiration': '3:20:00'},
    {'comm': 'BIW Handover', 'cn': ('BIW物资交接', ''), 'en': ('BIWHANDOVER', ''), 'jp': ('BIW物資交換', ''), 'tw': ('BIW物資交接', ''), 'duration': '3:00:00', 'expiration': '11:20:00'},
    {'comm': 'NYB Handover', 'cn': ('NYB物资交接', ''), 'en': ('NYBHANDOVER', ''), 'jp': ('NYB物資交換', ''), 'tw': ('NYB物資交接', ''), 'duration': '3:00:00', 'expiration': '11:20:00'},
    {'comm': 'Aiding Kongbanna', 'cn': ('支援恐班纳', ''), 'en': ('AIDINGKONGBANNA', ''), 'jp': ('離島兵員輸送', ''), 'tw': ('支援恐班納', ''), 'duration': '1:40:00', 'expiration': '5:00:00'},
    {'comm': 'Aiding Kapolo', 'cn': ('支援卡波罗岛', ''), 'en': ('AIDINGKAPOLO', ''), 'jp': ('外敵動静哨戒', ''), 'tw': ('支援卡波羅島', ''), 'duration': '1:40:00', 'expiration': '5:00:00'},
    {'comm': 'Destroy Enemy Force', 'cn': ('歼灭敌主力部队', ''), 'en': ('DESTROYENEMYFORCE', ''), 'jp': ('敵主力艦隊撃破', ''), 'tw': ('殲滅敵主力部隊', ''), 'duration': '2:00:00', 'expiration': '11:20:00'},
    {'comm': 'Enemy Attack Ⅱ', 'cn': ('敌袭', 'Ⅱ'), 'en': ('ENEMYATTACK', 'Ⅱ'), 'jp': ('敵襲', 'Ⅱ'), 'tw': ('敵襲', 'Ⅱ'), 'duration': '3:00:00', 'expiration': '11:20:00'},
    {'comm': 'BIW Holiday Escort', 'cn': ('BIW度假护卫', ''), 'en': ('BIWHOLIDAYESCORT', ''), 'jp': ('BIW休暇護衛', ''), 'tw': ('BIW度假護衛', ''), 'duration': '4:00:00', 'expiration': '9:00:00'},
    {'comm': 'NYB Holiday Escort', 'cn': ('NYB度假护卫', ''), 'en': ('NYBHOLIDAYESCORT', ''), 'jp': ('NYB休暇護衛', ''), 'tw': ('NYB度假護衛', ''), 'duration': '4:00:00', 'expiration': '9:00:00'},
    {'comm': 'Fleet Launch Ceremony', 'cn': ('联合观舰仪式', ''), 'en': ('FLEETLAUNCHCEREMONY', ''), 'jp': ('連合艦隊観艦式', ''), 'tw': ('聯合觀艦儀式', ''), 'duration': '6:00:00', 'expiration': '12:00:00'},
    {'comm': 'Aiding Manne Island', 'cn': ('支援马内岛', ''), 'en': ('AIDINGMANNEISLAND', ''), 'jp': ('外敵生態調査', ''), 'tw': ('支援馬內島', ''), 'duration': '2:00:00', 'expiration': '10:00:00'},
    {'comm': "Aiding St. Mary's Island", 'cn': ('支援玛丽岛', ''), 'en': ('AIDINGSTMARYSISLAND', ''), 'jp': ('前線部隊支援', ''), 'tw': ('支援瑪麗島', ''), 'duration': '2:00:00', 'expiration': '10:00:00'},
    {'comm': 'Cargo Defense Ⅲ', 'cn': ('保卫运输部队', 'Ⅲ'), 'en': ('CARGODEFENSE', 'Ⅲ'), 'jp': ('輸送部隊護衛', 'Ⅲ'), 'tw': ('保衛運輸部隊', 'Ⅲ'), 'duration': '2:40:00', 'expiration': '17:20:00'},
    {'comm': 'Merchant Rescue Ⅲ', 'cn': ('解救商船', 'Ⅲ'), 'en': ('MERCHANTRESCUE', 'Ⅲ'), 'jp': ('船団救出', 'Ⅲ'), 'tw': ('解救商船', 'Ⅲ'), 'duration': '4:00:00', 'expiration': '17:20:00'},
    {'comm': 'BIW Gear Research', 'cn': ('BIW装备研发', ''), 'en': ('BIWGEARRESEARCH', ''), 'jp': ('BIW装備試験', ''), 'tw': ('BIW裝備研發', ''), 'duration': '6:00:00', 'expiration': '6:40:00'},
    {'comm': 'NYB Gear Research', 'cn': ('NYB装备研发', ''), 'en': ('NYBGEARRESEARCH', ''), 'jp': ('NYB装備試験', ''), 'tw': ('NYB裝備研發', ''), 'duration': '6:00:00', 'expiration': '6:40:00'},
    {'comm': 'Aiding Isle of Man', 'cn': ('支援萌岛', ''), 'en': ('AIDINGISLEOFMAN', ''), 'jp': ('兵站航路確保', ''), 'tw': ('支援萌島', ''), 'duration': '2:30:00', 'expiration': '10:00:00'},
    {'comm': 'Aiding Kotlin Island', 'cn': ('支援特林岛', ''), 'en': ('AIDINGKOTLINISLAND', ''), 'jp': ('外敵中枢偵察', ''), 'tw': ('支援特林島', ''), 'duration': '2:30:00', 'expiration': '10:00:00'},
    {'comm': 'Destroy Enemy Elites', 'cn': ('歼灭敌精锐部队', ''), 'en': ('DESTROYENEMYELITES', ''), 'jp': ('敵精鋭部隊撃破', ''), 'tw': ('殲滅敵精銳部隊', ''), 'duration': '4:00:00', 'expiration': '17:20:00'},
    {'comm': 'Enemy Attack Ⅲ', 'cn': ('敌袭', 'Ⅲ'), 'en': ('ENEMYATTACK', 'Ⅲ'), 'jp': ('敵襲', 'Ⅲ'), 'tw': ('敵襲', 'Ⅲ'), 'duration': '6:00:00', 'expiration': '17:20:00'},
    {'comm': 'BIW Patrol Escort', 'cn': ('BIW巡视护卫', ''), 'en': ('BIWPATROLESCORT', ''), 'jp': ('BIW要人護衛', ''), 'tw': ('BIW巡視護衛', ''), 'duration': '8:00:00', 'expiration': '18:00:00'},
    {'comm': 'NYB Patrol Escort', 'cn': ('NYB巡视护卫', ''), 'en': ('NYBPATROLESCORT', ''), 'jp': ('NYB要人護衛', ''), 'tw': ('NYB巡視護衛', ''), 'duration': '8:00:00', 'expiration': '18:00:00'},
    {'comm': 'Alliance Launch Ceremony', 'cn': ('同盟观舰仪式', ''), 'en': ('ALLIANCELAUNCHCEREMONY', ''), 'jp': ('多国連合観艦式', ''), 'tw': ('同盟觀艦儀式', ''), 'duration': '12:00:00', 'expiration': '24:00:00'},
    {'comm': 'Self Training Ⅰ', 'cn': ('初阶自主训练', ''), 'en': ('SELFTRAINING', 'Ⅰ'), 'jp': ('初級自主訓練', ''), 'tw': ('初階自主訓練', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Self Training Ⅱ', 'cn': ('中阶自主训练', ''), 'en': ('SELFTRAINING', 'Ⅱ'), 'jp': ('中級自主訓練', ''), 'tw': ('中階自主訓練', ''), 'duration': '9:00:00', 'expiration': '0:00:00'},
    {'comm': 'Self Training Ⅲ', 'cn': ('高阶自主训练', ''), 'en': ('SELFTRAINING', 'Ⅲ'), 'jp': ('上級自主訓練', ''), 'tw': ('高階自主訓練', ''), 'duration': '10:00:00', 'expiration': '0:00:00'},
    {'comm': 'Defense Exercise Ⅰ', 'cn': ('初阶对抗演习', ''), 'en': ('DEFENSEEXERCISE', 'Ⅰ'), 'jp': ('初級対抗演習', ''), 'tw': ('初階對抗演習', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Defense Exercise Ⅱ', 'cn': ('中阶对抗演习', ''), 'en': ('DEFENSEEXERCISE', 'Ⅱ'), 'jp': ('中級対抗演習', ''), 'tw': ('中階對抗演習', ''), 'duration': '9:00:00', 'expiration': '0:00:00'},
    {'comm': 'Defense Exercise Ⅲ', 'cn': ('高阶对抗演习', ''), 'en': ('DEFENSEEXERCISE', 'Ⅲ'), 'jp': ('上級対抗演習', ''), 'tw': ('高階對抗演習', ''), 'duration': '10:00:00', 'expiration': '0:00:00'},
    {'comm': 'Tactical Class Ⅰ', 'cn': ('初阶战术课程', ''), 'en': ('TACTICALCLASS', 'Ⅰ'), 'jp': ('初級戦術課程', ''), 'tw': ('初階戰術課程', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Tactical Class Ⅱ', 'cn': ('中阶战术课程', ''), 'en': ('TACTICALCLASS', 'Ⅱ'), 'jp': ('中級戦術課程', ''), 'tw': ('中階戰術課程', ''), 'duration': '9:00:00', 'expiration': '0:00:00'},
    {'comm': 'Tactical Class Ⅲ', 'cn': ('高阶战术课程', ''), 'en': ('TACTICALCLASS', 'Ⅲ'), 'jp': ('上級戦術課程', ''), 'tw': ('高階戰術課程', ''), 'duration': '10:00:00', 'expiration': '0:00:00'},
    {'comm': 'Research Mission Ⅰ', 'cn': ('初阶科研任务', ''), 'en': ('RESEARCHMISSION', 'Ⅰ'), 'jp': ('初級科学研究', ''), 'tw': ('初階科研任務', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Research Mission Ⅱ', 'cn': ('中阶科研任务', ''), 'en': ('RESEARCHMISSION', 'Ⅱ'), 'jp': ('中級科学研究', ''), 'tw': ('中階科研任務', ''), 'duration': '9:00:00', 'expiration': '0:00:00'},
    {'comm': 'Research Mission Ⅲ', 'cn': ('高阶科研任务', ''), 'en': ('RESEARCHMISSION', 'Ⅲ'), 'jp': ('上級科学研究', ''), 'tw': ('高階科研任務', ''), 'duration': '10:00:00', 'expiration': '0:00:00'},
    {'comm': 'Cargo Transport Ⅰ', 'cn': ('初阶货物运输', ''), 'en': ('CARGOTRANSPORT', 'Ⅰ'), 'jp': ('初級貨物輸送', ''), 'tw': ('初階貨物運輸', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Cargo Transport Ⅱ', 'cn': ('中阶货物运输', ''), 'en': ('CARGOTRANSPORT', 'Ⅱ'), 'jp': ('中級貨物輸送', ''), 'tw': ('中階貨物運輸', ''), 'duration': '9:00:00', 'expiration': '0:00:00'},
    {'comm': 'Cargo Transport Ⅲ', 'cn': ('高阶货物运输', ''), 'en': ('CARGOTRANSPORT', 'Ⅲ'), 'jp': ('上級貨物輸送', ''), 'tw': ('高階貨物運輸', ''), 'duration': '10:00:00', 'expiration': '0:00:00'},
    {'comm': 'Tool Prep Ⅰ', 'cn': ('初阶工具整备', ''), 'en': ('TOOLPREP', 'Ⅰ'), 'jp': ('初級資材整理', ''), 'tw': ('初階工具整備', ''), 'duration': '8:00:00', 'expiration': '0:00:00'},
    {'comm': 'Tool Prep Ⅱ', 'cn': ('中阶工具整备', ''), 'en': ('TOOLPREP', 'Ⅱ'), 'jp': ('中級資材整理', ''), 'tw': ('中階工具整備', ''), 'duration': '9:00:00', 'expiration': '0:00:00'},
    {'comm': 'Tool Prep Ⅲ', 'cn': ('高阶工具整备', ''), 'en': ('TOOLPREP', 'Ⅲ'), 'jp': ('上級資材整理', ''), 'tw': ('高階工具整備', ''), 'duration': '10:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅰ', 'cn': ('日常资源开发', 'Ⅰ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅰ'), 'jp': ('日常資源開発', 'Ⅰ'), 'tw': ('日常資源開發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅰ', 'cn': ('日常资源开发', 'Ⅰ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅰ'), 'jp': ('日常資源開発', 'Ⅰ'), 'tw': ('日常資源開發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅱ', 'cn': ('日常资源开发', 'Ⅱ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅱ'), 'jp': ('日常資源開発', 'Ⅱ'), 'tw': ('日常資源開發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅱ', 'cn': ('日常资源开发', 'Ⅱ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅱ'), 'jp': ('日常資源開発', 'Ⅱ'), 'tw': ('日常資源開發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅰ', 'cn': ('日常资源开发', 'Ⅰ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅰ'), 'jp': ('日常資源開発', 'Ⅰ'), 'tw': ('日常資源開發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅰ', 'cn': ('日常资源开发', 'Ⅰ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅰ'), 'jp': ('日常資源開発', 'Ⅰ'), 'tw': ('日常資源開發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅰ', 'cn': ('日常资源开发', 'Ⅰ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅰ'), 'jp': ('日常資源開発', 'Ⅰ'), 'tw': ('日常資源開發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅱ', 'cn': ('日常资源开发', 'Ⅱ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅱ'), 'jp': ('日常資源開発', 'Ⅱ'), 'tw': ('日常資源開發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅱ', 'cn': ('日常资源开发', 'Ⅱ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅱ'), 'jp': ('日常資源開発', 'Ⅱ'), 'tw': ('日常資源開發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅱ', 'cn': ('日常资源开发', 'Ⅱ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅱ'), 'jp': ('日常資源開発', 'Ⅱ'), 'tw': ('日常資源開發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅲ', 'cn': ('日常资源开发', 'Ⅲ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅲ'), 'jp': ('日常資源開発', 'Ⅲ'), 'tw': ('日常資源開發', 'Ⅲ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅲ', 'cn': ('日常资源开发', 'Ⅲ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅲ'), 'jp': ('日常資源開発', 'Ⅲ'), 'tw': ('日常資源開發', 'Ⅲ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅳ', 'cn': ('日常资源开发', 'Ⅳ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅳ'), 'jp': ('日常資源開発', 'Ⅳ'), 'tw': ('日常資源開發', 'Ⅳ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅳ', 'cn': ('日常资源开发', 'Ⅳ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅳ'), 'jp': ('日常資源開発', 'Ⅳ'), 'tw': ('日常資源開發', 'Ⅳ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅲ', 'cn': ('日常资源开发', 'Ⅲ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅲ'), 'jp': ('日常資源開発', 'Ⅲ'), 'tw': ('日常資源開發', 'Ⅲ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅲ', 'cn': ('日常资源开发', 'Ⅲ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅲ'), 'jp': ('日常資源開発', 'Ⅲ'), 'tw': ('日常資源開發', 'Ⅲ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅲ', 'cn': ('日常资源开发', 'Ⅲ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅲ'), 'jp': ('日常資源開発', 'Ⅲ'), 'tw': ('日常資源開發', 'Ⅲ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅳ', 'cn': ('日常资源开发', 'Ⅳ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅳ'), 'jp': ('日常資源開発', 'Ⅳ'), 'tw': ('日常資源開發', 'Ⅳ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅳ', 'cn': ('日常资源开发', 'Ⅳ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅳ'), 'jp': ('日常資源開発', 'Ⅳ'), 'tw': ('日常資源開發', 'Ⅳ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅳ', 'cn': ('日常资源开发', 'Ⅳ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅳ'), 'jp': ('日常資源開発', 'Ⅳ'), 'tw': ('日常資源開發', 'Ⅳ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅴ', 'cn': ('日常资源开发', 'Ⅴ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅴ'), 'jp': ('日常資源開発', 'Ⅴ'), 'tw': ('日常資源開發', 'Ⅴ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅴ', 'cn': ('日常资源开发', 'Ⅴ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅴ'), 'jp': ('日常資源開発', 'Ⅴ'), 'tw': ('日常資源開發', 'Ⅴ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅵ', 'cn': ('日常资源开发', 'Ⅵ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅵ'), 'jp': ('日常資源開発', 'Ⅵ'), 'tw': ('日常資源開發', 'Ⅵ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅵ', 'cn': ('日常资源开发', 'Ⅵ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅵ'), 'jp': ('日常資源開発', 'Ⅵ'), 'tw': ('日常資源開發', 'Ⅵ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅴ', 'cn': ('日常资源开发', 'Ⅴ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅴ'), 'jp': ('日常資源開発', 'Ⅴ'), 'tw': ('日常資源開發', 'Ⅴ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅴ', 'cn': ('日常资源开发', 'Ⅴ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅴ'), 'jp': ('日常資源開発', 'Ⅴ'), 'tw': ('日常資源開發', 'Ⅴ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅴ', 'cn': ('日常资源开发', 'Ⅴ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅴ'), 'jp': ('日常資源開発', 'Ⅴ'), 'tw': ('日常資源開發', 'Ⅴ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅵ', 'cn': ('日常资源开发', 'Ⅵ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅵ'), 'jp': ('日常資源開発', 'Ⅵ'), 'tw': ('日常資源開發', 'Ⅵ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅵ', 'cn': ('日常资源开发', 'Ⅵ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅵ'), 'jp': ('日常資源開発', 'Ⅵ'), 'tw': ('日常資源開發', 'Ⅵ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Daily Resource Extraction Ⅵ', 'cn': ('日常资源开发', 'Ⅵ'), 'en': ('DAILYRESOURCEEXTRACTION', 'Ⅵ'), 'jp': ('日常資源開発', 'Ⅵ'), 'tw': ('日常資源開發', 'Ⅵ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅰ', 'cn': ('高阶战术研发', 'Ⅰ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅰ'), 'jp': ('覚醒実証研究', 'Ⅰ'), 'tw': ('高階戰術研發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅰ', 'cn': ('高阶战术研发', 'Ⅰ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅰ'), 'jp': ('覚醒実証研究', 'Ⅰ'), 'tw': ('高階戰術研發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅰ', 'cn': ('高阶战术研发', 'Ⅰ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅰ'), 'jp': ('覚醒実証研究', 'Ⅰ'), 'tw': ('高階戰術研發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅰ', 'cn': ('高阶战术研发', 'Ⅰ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅰ'), 'jp': ('覚醒実証研究', 'Ⅰ'), 'tw': ('高階戰術研發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅰ', 'cn': ('高阶战术研发', 'Ⅰ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅰ'), 'jp': ('覚醒実証研究', 'Ⅰ'), 'tw': ('高階戰術研發', 'Ⅰ'), 'duration': '1:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅱ', 'cn': ('高阶战术研发', 'Ⅱ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅱ'), 'jp': ('覚醒実証研究', 'Ⅱ'), 'tw': ('高階戰術研發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅱ', 'cn': ('高阶战术研发', 'Ⅱ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅱ'), 'jp': ('覚醒実証研究', 'Ⅱ'), 'tw': ('高階戰術研發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅱ', 'cn': ('高阶战术研发', 'Ⅱ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅱ'), 'jp': ('覚醒実証研究', 'Ⅱ'), 'tw': ('高階戰術研發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅱ', 'cn': ('高阶战术研发', 'Ⅱ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅱ'), 'jp': ('覚醒実証研究', 'Ⅱ'), 'tw': ('高階戰術研發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
    {'comm': 'Awakening Tactical Research Ⅱ', 'cn': ('高阶战术研发', 'Ⅱ'), 'en': ('AWAKENINGTACTICALRESEARCH', 'Ⅱ'), 'jp': ('覚醒実証研究', 'Ⅱ'), 'tw': ('高階戰術研發', 'Ⅱ'), 'duration': '2:00:00', 'expiration': '0:00:00'},
)
